### ISSUE TITLE
On one of the TODO's in the README

### ISSUE THREAD

**Issue by loneicewolf** [nisay759/sudo-backdoor#2]
Hello,

#### first things first, as to say'

I have long found your repo helpful (although not specifically this one, but the `linux-rootkits` one. Which I have improved as well; a bit). Keep it up, with all those projects and your blog! Respect. 💯 

#### About the "encryption" on the TODO

>  Encrypt the password before sending it

I am very much into cryptography (not really particularly  "programming in it" but, I find it a fascinating topic, and have some experience in the topic) I was just gonna ask first, before making the pull/improvement (that I am planning of doing) and that question is:

### is this project considered "serious" ? 

What I mean by that is, if it isn't some POC script, or something on those lines, then I will take that into account and make my contribution a bit more complex.

If it is a POC script, or a POC project mostly for fun, then I plan to still make some contribution, but more easily understood.

### No stress in answering, I am myself slow in replying.

_____
*footnotes*
- POC - Proof Of Concept

**Comment by loneicewolf** [comment]
### Additionally;

also, while I am at it - I also ask is it **only** cryptography, or have you any plans of making obfuscation and covert related things as well? Such as,
- Steganography (which might or might not be only trough a picture)
- Obfuscation (which as cryptography, can be "in layers")
- speaking of which, what is your "general idea" how the "cryptography" in your project should work? E.g,  symmetric cryptography or asymmetric? (AES, RSA&DH?)

---

**Comment by loneicewolf** [comment]
Replying to the first post I posted; to clarify:
In your linux-rootkits repo, you explicitly stated

> These rootkits are by no mean real-world rootkits. They have been kept to the minimum and should be used for educational purposes only.
- [nisay759 linux-rootkits - At GitHub](https://github.com/nisay759/linux-rootkits)

Which is my question but if this project also is one :)

*This is the last comment. Have a great day!*

**Comment by nisay759** [comment]
Hello @loneicewolf !
Thank you for your interest in this repo.

> **is this project considered "serious" ?**

I could see some post-exploitation scenarios where you'd want the password of a user for privilege escalation purposes. Personally, I hadn't had the chance to use this script yet, but I think it might come in handy one day :)

> **About the "encryption" on the TODO**

I put that in the TODO because I wasn't comfortable with sending the cleartext password over with `nc`. The easiest way to add encryption is probably to send the password to a user-controlled server over HTTPS.

The script should stay simple as any long computation that can slow down the output might alert the victim, so I am not sold on implementing encryption inside a bash script.

Also, the password extraction should be always adapted depending on your needs and the target environment: The binaries on the target system might be different, the egress traffic could be filtered, etc. Therefore, the encryption (or no encryption) depends on the attacker and the target environment, and I don't think there's a need to implement a _specific_ extraction method.

Cheers !

**Comment by loneicewolf** [comment]
@nisay759  Hello!

Oh, I see - thanks for elaborating! :) 
Good luck on everything!
and I am happy you could read my (fuzzily written) "issue" 👍🏻 

Cheers back on you! ^^
